### ISSUE TITLE
请问怎么使用呢

### ISSUE THREAD

**Issue by 362442340** [jianyun8023/homekit-diy#1]

**Comment by jianyun8023** [comment]
两种方式

## docker 命令：
`docker run -d --net=host -e MIIO_HOST=192.168.1.1 MIIO_TOKEN=bd5331094c79167c30118549fd53137d yihy/homekit-mifan-server:latest`

MIIO_HOST换成 ip
MIIO_TOKEN换成你的token。


## 使用python直接跑：

先安装python3和python的依赖  `pip3 install python-miio HAP-python[QRCode]`

`python3 mifan.py  --host 192.168.1.1 --token bd5331094c79167c30118549fd53137d`
